### ISSUE TITLE
Tag in issue/PR in yui0303

### ISSUE THREAD

**Issue by yungyuc** [yui0303/Matrix-Diagonalization#1]
Please see https://github.com/yxuan0329/R-tree-Search-Engine/issues/1 .  It's great to see your code in the repository.  Making PR and tagging me provides me an opportunity to review your code.

**Comment by yungyuc** [comment]
@yui0303 could you please take a look at https://github.com/Yvonne-ul6u45p/ContiguousArray-MultiDim-Index-Calculation/pull/2 and file PRs in the same way?  Your PRs will help me adding comments.

**Comment by yui0303** [comment]
@yungyuc Oh, thanks for reminding me. This week was very busy. I'll complete the PR in a few days.

**Comment by yungyuc** [comment]
No problem, @yui0303 .  Keep your own pace.

**Comment by yui0303** [comment]
@yungyuc I added the PR. I wonder whether this is correct?

**Comment by yui0303** [comment]
@yungyuc. I may have finished the serial version of QR decomposition in this PR.

https://github.com/yui0303/Matrix-Diagonalization/pull/2

**Comment by yungyuc** [comment]
@yui0303 it is nice.  And I guess you perhaps have started to make slides?

**Comment by yui0303** [comment]
@yungyuc Yeah, I have written something.
